export const callReportMock = {
  current_page: 1,
  from: 1,
  last_page: 4622,
  path: 'https://qa.yieldpro.io/api/data/calls',
  per_page: 10,
  to: 10,
  total: 46220,
  data: [
    {
      id: 4236022502,
      url: null,
      transcript: null,
      billable: null,
      status_t: null,
      multiple: null,
      did_number_id: 2099067455,
      cpl: '0.00',
      vendors_td: 'JDE',
      status: 'Contact',
      buyer_id: 27672,
      buyers: 'MNJD/VTP-DHI-ACA-TF-CPA',
      revenue: '0.00',
      phone_id: 4705061120,
      terminating_phone: '+18778670266',
      durations: '03:37',
      created_at: null,
      offers: 'ACA Calls',
      offer_id: 20002,
      pub_list_id: 1,
      date_sale: '2024-09-26 10:09:37',
      calls: 1,
      converted: 0,
      traffic_source_id: 10802,
      insurance: 'N/A',
      insurance_value: null,
      insurance_name: '-',
      state: 'GA',
    },
    {
      id: 4236019942,
      url: 'https://massnexus-llc.trackdrive.com/calls/recordings/32529907-1994-430a-8803-a749b205f16a/d9a14076-53af-425f-a91c-78dcef659e96',
      transcript: 'Hello, this is Collin, who I have the pleasure of speaking with today.',
      billable: 0,
      status_t: 1,
      multiple: {
        data: "## 1. Lead Type and Participants Identification\n- **Lead Type:** Inbound\n- **Total participants in the call:** 1\n  - **Call Center Agent:** Collin\n## 2. Conversation Effectiveness Check\n- **Was there a meaningful and coherent conversation?** No\n- **Details**: The transcript is too short to determine if a meaningful and coherent conversation occurred.\n## 3. Lead's Personal Information\n- **First Name(s):** N/A\n- **Last Name(s):** N/A\n- **Full Address:** N/A\n- **State:** N/A\n- **Zip Code:** N/A\n- **Date of Birth:** N/A\n- **Age:** N/A\n- **US Citizen:** N/A\n- **Valid SSN:** N/A\n- **SSN:** N/A\n- **Currently Employed:** N/A\n- **Household or Combined Annual Income:** N/A\n- **Individual Annual Income:** N/A\n## 4. Technical Issues, On Hold, Call Drops, Dear Air, Hung Up, or Follow-up plans\n- **Was there any technical issue, on hold, call drops, dear air, hung up or any follow-up plan to consider?** No\n- **Details**: The transcript is too short to determine any issues or follow-up plans.\n## 5. Sentiment Analysis\n- **Sentiment:** N/A\n- **Details**: The transcript is too short to determine the sentiment.\n## 6. Rudeness or Mistreatment Detection\n- **Was there any rudeness or mistreatment?** No\n- **Details**: The transcript is too short to determine any rudeness or mistreatment.\n## 7. Existing and Current Insurance Policy Check\n- **Did the lead mention having an existing and current health insurance policy during this conversation?** N/A\n- **Details**: The transcript is too short to determine if the lead mentioned having an existing and current health insurance policy.\n## 8. Pre-qualification Assessment\n- **Does the lead pre-qualify?** No\n- **Reason(s):** The transcript is too short to analyze.\n- **Details**: The transcript is too short to determine if the lead pre-qualifies.\n## 9. Sales Evaluation\n- **Was a sale made?** No\n- **Details**: The transcript is too short to determine if a sale was made.\n## 10. Call Ending Analysis\n- **Did the call end sooner than expected?** Yes\n- **Reason(s):** Transcript too short\n- **Details**: The transcript is too short to determine the reason for the call ending.",
        call_issues:
          '## 4. Technical Issues, On Hold, Call Drops, Dear Air, Hung Up, or Follow-up plans\n- **Was there any technical issue, on hold, call drops, dear air, hung up or any follow-up plan to consider?** No\n- **Details**: The transcript is too short to determine any issues or follow-up plans.',
        mistreatment:
          '## 6. Rudeness or Mistreatment Detection\n- **Was there any rudeness or mistreatment?** No\n- **Details**: The transcript is too short to determine any rudeness or mistreatment.',
        personal_data:
          "## 3. Lead's Personal Information\n- **First Name(s):** N/A\n- **Last Name(s):** N/A\n- **Full Address:** N/A\n- **State:** N/A\n- **Zip Code:** N/A\n- **Date of Birth:** N/A\n- **Age:** N/A\n- **US Citizen:** N/A\n- **Valid SSN:** N/A\n- **SSN:** N/A\n- **Currently Employed:** N/A\n- **Household or Combined Annual Income:** N/A\n- **Individual Annual Income:** N/A",
        sale_analysis:
          '## 9. Sales Evaluation\n- **Was a sale made?** No\n- **Details**: The transcript is too short to determine if a sale was made.',
        call_issues_result: 'NO',
        existing_insurance:
          '## 7. Existing and Current Insurance Policy Check\n- **Did the lead mention having an existing and current health insurance policy during this conversation?** N/A\n- **Details**: The transcript is too short to determine if the lead mentioned having an existing and current health insurance policy.',
        sentiment_analysis:
          '## 5. Sentiment Analysis\n- **Sentiment:** N/A\n- **Details**: The transcript is too short to determine the sentiment.',
        mistreatment_result: 'NO',
        call_ending_analysis:
          '## 10. Call Ending Analysis\n- **Did the call end sooner than expected?** Yes\n- **Reason(s):** Transcript too short\n- **Details**: The transcript is too short to determine the reason for the call ending.',
        sale_analysis_result: 'NO',
        sale_analysis_details: 'The transcript is too short to determine if a sale was made.',
        existing_insurance_name: '',
        call_ending_sooner_result: true,
        existing_insurance_result: 'N/A',
        call_ending_sooner_reasons: [
          {
            reason: 'The transcript is too short to determine the reason for the call ending.',
            category: 'Transcript too short',
          },
        ],
        conversation_effectiveness:
          '## 2. Conversation Effectiveness Check\n- **Was there a meaningful and coherent conversation?** No\n- **Details**: The transcript is too short to determine if a meaningful and coherent conversation occurred.',
        lead_type_and_participants:
          '## 1. Lead Type and Participants Identification\n- **Lead Type:** Inbound\n- **Total participants in the call:** 1\n  - **Call Center Agent:** Collin',
        pre_qualification_analysis:
          '## 8. Pre-qualification Assessment\n- **Does the lead pre-qualify?** No\n- **Reason(s):** The transcript is too short to analyze.\n- **Details**: The transcript is too short to determine if the lead pre-qualifies.',
        conversation_effectiveness_result: 'NO',
        pre_qualification_analysis_result: 'NO',
      },
      did_number_id: 2099067455,
      cpl: '0.00',
      vendors_td: 'JDE',
      status: 'Contact',
      buyer_id: 27682,
      buyers: 'MNJD/VTP-GMH-VP2-ACA-TF',
      revenue: '0.00',
      phone_id: 3162266821,
      terminating_phone: 'sip:9544407417@sip.212042.chasedatacorp.com',
      durations: '00:06',
      created_at: null,
      offers: 'ACA Calls',
      offer_id: 20002,
      pub_list_id: 1,
      date_sale: '2024-09-26 10:09:10',
      calls: 1,
      converted: 0,
      traffic_source_id: 10802,
      insurance: 'N/A',
      insurance_value: 3,
      insurance_name: '',
      state: 'KS',
    },
  ],
  average: {
    total_spend: 105485.34,
    total_revenue: 206802.5,
    total_profit: 101317.16,
    total_roi: 96.05,
    total_convertion: 0,
    total_leadstocall: 0.49,
    total_leads: 22459,
    total_calls: '46220',
    total_answered: 0,
    total_billable: '4776',
    total_answeredtobillable: 0,
    total_callstoanswered: 0,
    total_cpl: 4.7,
    total_cpc: 0,
    total_cps: 22.09,
    total_rpl: 9.21,
    total_rpc: 0,
    total_rps: 43.3,
    total_spend_leads: 236.94,
    total_spend_calls: 105248.4,
    total_uniquecalls: 0,
  },
  sum: {
    total_revenue: 206802.5,
    total_spend: 105485.34,
  },
  totals_diff: {
    total_spend: -49.8,
    total_revenue: -35.2,
    total_profit: -7.2,
    total_roi: 84.6,
    total_convertion: 0,
    total_leadstocall: 0.49,
    total_leads: -69.4,
    total_calls: -56.5,
    total_answered: 0,
    total_billable: -37.7,
    total_answeredtobillable: 0,
    total_callstoanswered: 0,
    total_cpl: 4.7,
    total_cpc: 0,
    total_cps: 22.09,
    total_rpl: 9.21,
    total_rpc: 0,
    total_rps: 43.3,
    total_spend_leads: 236.94,
    total_spend_calls: 105248.4,
    total_uniquecalls: 0,
  },
}

